#!/bin/bash

echo "Enabling power saving mode"
notify-send -a "Power Save" -i battery "Turned on" "Disabling features to conserve battery"
touch /tmp/power-save-enabled

# Lower refresh rate of built-in monitor
hyprctl keyword monitor "eDP-1,2560x1600@60,0x0,1.6" >>/dev/null

# Disable animations
hyprctl keyword animations:enabled false >>/dev/null

# Floating windows don't blur windows under them.
hyprctl keyword decoration:blur:xray true >>/dev/null

# Disable drop shadows
hyprctl keyword decoration:shadow:enabled false >>/dev/null

systemctl --user stop syncthing >>/dev/null
sudo systemctl stop nordvpnd.service

sudo pkill evolution
pkill swww-daemon
pkill -f set-wallpaper-on-workspace-change-daemon

# Dim screen
# brightnessctl set 50%

# Example GPU tweak (optional, depends on hardware/drivers)
# nvidia-smi -pm 1 && nvidia-smi -pl 40
