#!/bin/bash

echo "Enabling power saving mode"
notify-send -a "Power Save" -i battery "Turned on" "Disabling features to conserve battery"
touch /tmp/power-save-enabled

echo Lowering refresh rate of monitor:
hyprctl keyword monitor "eDP-1,2560x1600@60,0x0,1.6"

echo Disable Hyprland pretty animations
hyprctl keyword animations:enabled false

echo Disable blur under floating windows
hyprctl keyword decoration:blur:xray true

echo Disable drop shadows
hyprctl keyword decoration:shadow:enabled false

echo killing syncthing
systemctl --user stop syncthing

echo killing nordvpn
sudo systemctl stop nordvpnd.service

echo killing evolution
sudo pkill evolution

echo stopping background switcher, and swww-daemon
pkill swww-daemon
pkill -f set-wallpaper-on-workspace-change-daemon

# killing beeper
pkill beeper

# If bluetooth is turned on, but nothing is connected, then shut it down.
if [ -z "$(bluetoothctl devices Connected)" ]; then
	echo Nothing connected to bluetooth, so shutting it off.
	bluetoothctl power off
else
	echo Bluetooth connected, leaving on.
fi

# If not connected to wifi, shut down wifi
if [ -z "$(iwctl station wlan0 show | grep connected)" ]; then
	echo Not connected to wifi, shutting it down
else
	echo WiFi connected, leaving on.
fi

# Dim screen
brightnessctl set 20-

# Example GPU tweak (optional, depends on hardware/drivers)
# nvidia-smi -pm 1 && nvidia-smi -pl 40
