#!/usr/bin/env bash
set -e

repo="."

# If first argument is not a flag, treat it as repo path
if [[ $# -gt 0 && ! "$1" =~ ^- ]]; then
    repo="$1"
    shift
fi

repo="$(realpath "$repo")"
repo_name="$(basename "$repo")"
caption_file="/tmp/gource-commitmsg-${repo_name}.txt"

# Build caption file with line statistics
git -C "$repo" log \
    --reverse \
    --no-merges \
    --pretty=format:'COMMIT|%at|%s' \
    --numstat |
    awk -F'\t' '
BEGIN {
    add=0; del=0;
}
$0 ~ /^COMMIT\|/ {
    if (NR>1) {
        printf "%s|%s (+%d/-%d)\n", ts, msg, add, del;
    }
    split($0, parts, "|");
    ts = parts[2];
    msg = parts[3];
    add=0; del=0;
    next;
}
NF==3 {
    if ($1 ~ /^[0-9]+$/) add += $1;
    if ($2 ~ /^[0-9]+$/) del += $2;
}
END {
    printf "%s|%s (+%d/-%d)\n", ts, msg, add, del;
}
' >"$caption_file"

echo "Caption file written to: $caption_file"

# Run gource with passthrough args
gource \
    --high-dpi \
    --caption-file "$caption_file" \
    "$@" \
    "$repo"
