#!/bin/bash
# Convenience function for adding a file to this dotfiles registry :D
if ! [[ $1 == ~/* ]]; then
    echo "Provide filename in format ~/[...]"
    exit 2
fi

homedirlen="${#HOME}"
target="${HOME}/dotfiles${1:$homedirlen}"
mkdir -p `dirname $target`
mv $1 $target
stow-dotfiles
echo "moved to $target"
