#!/bin/bash

function print_help() {
            printf "\
Usage: set-keyboard [OPTION]\n\
\n\
Options:\n\
    -c  Set to modified colemak-CAWS for JIS.\n\
    -q  Set to QWERTY.\n"
}
while getopts 'hcq' OPTION
do
    case "$OPTION" in
        h)
            print_help
            exit 0
            ;;
        c)
            setxkbmap -model 'pc104awide' -layout 'colemak(cmk_jised)' -option 'misc:extend,lv5:caps_switch_lock,compose:menu,misc:cmk_curl_dh,misc:sym_wide-104,shift:both_capslock'
            echo "Set keyboard to modified colemak-CAWS for JIS"
            exit 0
            ;;
        q)
            setxkbmap -model pc104 -layout us -variant intl -option
            echo "Set keyboard to QWERTY"
            exit 0
            ;;
        ?)
            print_help
            exit 1
            ;;
    esac
done

print_help
exit 1
