[Personal]
source        = maildir://~/mail/personal
outgoing      = smtps+plain://aida@osphire.com@smtp.strato.de:465
outgoing-cred-cmd = secret-tool lookup password personalmail
default       = INBOX
from          = aida <aida@osphire.com>
copy-to       = Sent

[Accounts]
source        = maildir://~/mail/accounts
# Remove the outgoing? I don't send emails with this typically
#outgoing      = smtps+plain://accounts@osphire.com@smtp.strato.de:465
#outgoing-cred-cmd = secret-tool lookup password accountsmail
default       = INBOX
from          = aida <aida@osphire.com>


[GFwd]
source        = maildir://~/mail/gforward/
default       = INBOX
from          = aida <aida@osphire.com>
