# See `man fuzzel.ini`
font=Avenir Next LT Pro:size=14,Iosevka Nerd Font:size=14
icon-theme=Papirus-Dark
width=40
fields=name,generic,comment,categories,filename,keywords
line-height=42
lines = 10

[key-bindings]
cancel=Control+c Escape
