"""
This type stub file was generated by pyright.
"""

"""
Downloads an iCal url or reads an iCal file.
"""
def apple_data_fix(content):
    """
    Fix Apple tzdata bug.

    :param content: content to fix
    :return: fixed content
    """
    ...

def apple_url_fix(url):
    """
    Fix Apple URL.

    :param url: URL to fix
    :return: fixed URL
    """
    ...

class ICalDownload:
    """
    Downloads or reads and decodes iCal sources.
    """
    def __init__(self, http=..., encoding=...) -> None:
        ...
    
    def data_from_url(self, url, apple_fix=...):
        """
        Download iCal data from URL.

        :param url: URL to download
        :param apple_fix: fix Apple bugs (protocol type and tzdata in iCal)
        :return: decoded (and fixed) iCal data
        """
        ...
    
    def data_from_file(self, file, apple_fix=...): # -> str:
        """
        Read iCal data from file.

        :param file: file to read
        :param apple_fix: fix wrong Apple tzdata in iCal
        :return: decoded (and fixed) iCal data
        """
        ...
    
    def data_from_string(self, string_content, apple_fix=...):
        ...
    
    def decode(self, content, apple_fix=...):
        """
        Decode content using the set charset.

        :param content: content do decode
        :param apple_fix: fix Apple txdata bug
        :return: decoded (and fixed) content
        """
        ...
    


