format = """
[██](#89dceb)\
 $username\
[](bg:#89b4fa fg:#89dceb)\
$directory\
[](fg:#89b4fa bg:#eba0ac)\
$git_branch\
$git_status\
[](fg:#eba0ac bg:#7f849c)\
$rust\
[](fg:#7f849c bg:#181825)\
$time\
[ ](fg:#181825)\
\n$character"""

[username]
show_always = true
style_user = "bg:#89dceb"
style_root = "fg:#9A348E"
format = '[$user ]($style)'
disabled = false

[directory]
style = "fg:#e3e5e5 bg:#89b4fa"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#eba0ac"
format = '[[ $symbol $branch ](fg:#89b4fa bg:#eba0ac)]($style)'

[git_status]
style = "bg:#eba0ac"
format = '[[($all_status$ahead_behind )](fg:#89b4fa bg:#eba0ac)]($style)'


[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#181825"
format = '[[  $time ](fg:#a0a9cb bg:#181825)]($style)'
