#!/bin/bash
hyprctl keyword input:kb_variant cmk_ed_dh
hyprctl keyword input:kb_model pc104awide
hyprctl keyword input:kb_options misc:extend,lv5:caps_switch_lock,grp:lalt_toggle,compose:menu,misc:sym_wide-104,shift:both_capslock
echo "Set keyboard to colemak-CAWS"
exit 0