#!/bin/bash
hyprctl keyword input:kb_model pc104
hyprctl keyword input:kb_variant intl
hyprctl keyword input:kb_options ""
echo "Set keyboard to QWERTY"
notify-send -i "/usr/share/icons/Papirus/64x64/devices/keyboard.svg" "Keyboard: QWERTY"