#!/bin/bash
# If currently in colemak, go to qwerty, and vice versa. To be used for little switcher button.
if hyprctl getoption input:kb_variant | grep -q cmk
then
    ~/scripts/hyprland-qwerty > /dev/null
    echo QWERTY
else
    ~/scripts/hyprland-colemak > /dev/null
    echo CMK
fi