#!/bin/bash
# Queries mpd, and saves the album art in /tmp/music so that is can be used by other programs


# Cache music directory, because file paths listed by mpc are relative to this.
MUSIC_DIR=$(< "$HOME/.config/mpd/mpd.conf" grep music_directory | cut -d " " -f 2 | sed 's/"//g');
DEFAULT_COVER="$HOME/os/img/default_music_cover.png"

mkdir /tmp/music
PREVIOUS_TRACK_LOCAL_FILENAME="";
echo "$MUSIC_DIR"
while : ; do
        # Wait until some event occurs. Note that this is fired also for pausing etc.
        mpc idle player
        CURRENT_TRACK_LOCAL_PATH=$(mpc current --format "%file%");
        # Check if the song that is being played actually changed (is the path different?)
        if [ "$PREVIOUS_TRACK_LOCAL_FILENAME" = "$CURRENT_TRACK_LOCAL_PATH" ]; then
                continue
        fi
        PREVIOUS_TRACK_LOCAL_FILENAME=$CURRENT_TRACK_LOCAL_PATH

        # If playback has stopped, the current file path will be empty. Then, just delete the image.
        if [ "$CURRENT_TRACK_LOCAL_PATH" = "" ]; then
                rm $(find /tmp/music -iname "cover.*")
                continue
        fi

        # First see if there is a cover.*, or folder.*, and if there is, use that. Here * = .png, .PNG, .jpg, .JPG.
        # Search case insensitive, match any extension. Use first hit. png should come before jpg.
        CURRENT_TRACK_PATH="$MUSIC_DIR/$CURRENT_TRACK_LOCAL_PATH";
        CURRENT_TRACK_PATH="${CURRENT_TRACK_PATH/#\~/$HOME}" # Manually expanding the ~ to /home/(...)
        ALBUM_PATH=$(dirname "$CURRENT_TRACK_PATH")
        ALBUM_ART=$(find "$ALBUM_PATH" -iname "cover.*" | head -1)
        if [ "$ALBUM_ART" = "" ]; then
                ALBUM_ART=$(find "$ALBUM_PATH" -iname "folder.*" | head -1)
        fi
        # Store it in the cache folder if it exists.
        if [ "$ALBUM_ART" ]; then
                cover_filename=$(basename "$ALBUM_ART" | tr '[:upper:]' '[:lower:]')
                cover_extension="${cover_filename##*.}"
                cp "$ALBUM_ART" "/tmp/music/cover.$cover_extension"
                continue
        fi


        # Check if it has embedded album art.

        # If no cover art, use the the default album art.

        echo No album art found
done