#!/bin/bash

function print_help() {
            printf "\
Sets keyboard for hyprland.
Usage: set-keyboard [OPTION]\n\
\n\
Options:\n\
    -c  Set to modified colemak-CAWS for JIS.\n\
    -q  Set to QWERTY.\n"
}
while getopts 'hcq' OPTION
do
    case "$OPTION" in
        h)
            print_help
            exit 0
            ;;
        c)
            hyprctl keyword input:kb_variant cmk_ed_dh
            hyprctl keyword input:kb_model pc104awide
            hyprctl keyword input:kb_options misc:extend,lv5:caps_switch_lock,grp:lalt_toggle,compose:menu,misc:sym_wide-104,shift:both_capslock
            echo "Set keyboard to colemak-CAWS"
            exit 0
            ;;
        q)
            hyprctl keyword input:kb_model pc104
            hyprctl keyword input:kb_variant intl
            hyprctl keyword input:kb_options ""
            echo "Set keyboard to QWERTY"
            exit 0
            ;;
        ?)
            print_help
            exit 1
            ;;
    esac
done

print_help
exit 1